"""ME 465 / MME 565 simulation labs: the course scene, and the few helpers a lab needs.

The robotics and the simulator bridge are the `screws` package; this module only
knows where the course scene is and how a lab day opens and closes it.

    from me465 import open_lab, settle, close

    scene, arm = open_lab()          # CoppeliaSim running, the UR5 scene loaded, stepping
    arm.command_positions([0, 0, 0, 0, 0, 0])
    settle(scene, arm)
    print(arm.theta(), arm.tip_frame())
    close(scene)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

#: The course scene, generated by `me465.build_scene` from CoppeliaSim's own UR5.
SCENE = Path(__file__).resolve().parent / "scenes" / "ur5.ttt"

#: Height of the stand the UR5 is bolted to, in metres. MR's {s} sits on top of it.
PEDESTAL = 0.4


def open_lab(path: str | Path = SCENE):
    """Connect, load the course scene, and start it in stepping mode.

    Returns `(scene, arm)`: a `screws.coppelia.Scene` and the UR5 as an `Arm`
    in position mode. Anything a previous run left going is stopped first.
    """
    from screws.coppelia import Scene

    scene = Scene()
    sim = scene.sim
    if sim.getSimulationState() != sim.simulation_stopped:
        scene.stop()
        while sim.getSimulationState() != sim.simulation_stopped:
            pass
    sim.loadScene(str(Path(path).resolve()))
    arm = scene.arm("/UR5")
    arm.mode("position")
    scene.start()
    return scene, arm


def settle(scene, arm, seconds: float = 6.0, tol: float = 1e-5) -> np.ndarray:
    """Step until the joints stop moving (or `seconds` pass); return where they stopped."""
    previous = arm.theta()
    for _ in range(max(1, int(seconds / scene.dt))):
        scene.step()
        now = arm.theta()
        if np.max(np.abs(now - previous)) < tol:
            return now
        previous = now
    return previous


def close(scene) -> None:
    """Stop the simulation and let go of it, so the next run starts clean."""
    scene.__exit__(None, None, None)


def joint_sliders(scene, arm, *, continuous: bool = False, settle_seconds: float = 1.5, degrees: bool = True):
    """Six sliders that drive the arm: move one and the simulated joints follow.

    Each change commands the six angles and steps the simulation until the joints
    stop (up to `settle_seconds`), then prints where the tool ended up. By default a
    slider sends its value when you release it; `continuous=True` sends while you
    drag, which is livelier and slower. Returns the sliders, so a script can read or
    set them. Needs ipywidgets (installed with the course environment).
    """
    import ipywidgets as widgets
    from IPython.display import display

    unit, lo, hi, step = ("deg", -180.0, 180.0, 1.0) if degrees else ("rad", -np.pi, np.pi, 0.02)
    start = arm.theta()
    sliders = [
        widgets.FloatSlider(
            value=float(np.degrees(start[i]) if degrees else start[i]),
            min=lo, max=hi, step=step,
            description=f"θ{i + 1} ({unit})",
            continuous_update=continuous,
            readout_format=".0f" if degrees else ".2f",
            layout=widgets.Layout(width="480px"),
        )
        for i in range(arm.n)
    ]
    out = widgets.Output()

    def send(_change=None):
        values = np.array([s.value for s in sliders], dtype=float)
        theta = np.radians(values) if degrees else values
        arm.command_positions(theta)
        measured = settle(scene, arm, seconds=settle_seconds)
        with out:
            out.clear_output(wait=True)
            print("joints stopped at (deg):", np.round(np.degrees(measured), 1))
            print("tool frame, in the simulator's world frame:\n", np.round(arm.tip_frame(), 3))

    for s in sliders:
        s.observe(send, names="value")
    display(widgets.VBox([*sliders, out]))
    send()
    return sliders
